### 04-03-2020

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
hr_data = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/HR_comma_sep.csv.txt')
hr_data.rename(columns={'sales':'dept'},inplace=True)

In [3]:
hr_data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years   dept  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [4]:
hr_data.left.value_counts()

0    11428
1     3571
Name: left, dtype: int64

### Inferances
Target(left) is discrete in nature so a classification problem

In [5]:
target_data = hr_data.left

### Taking care of categorical columns
dept & salary is categorical
ML algorithms only understands numerical data
We will use preprocessor LabelEncoder to convert this into numerical data


In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le_salary = LabelEncoder()

In [8]:
le_salary.fit(hr_data.salary)

LabelEncoder()

In [9]:
le_salary.transform(['low','medium','low'])

array([1, 2, 1], dtype=int32)

In [10]:
hr_data['salary_en'] = le_salary.transform(hr_data.salary)

In [11]:
le = LabelEncoder()

In [12]:
le.fit_transform(hr_data.salary)

array([1, 2, 2, ..., 1, 1, 1])

In [13]:
le_dept = LabelEncoder()

In [14]:
le_dept.fit(hr_data.dept)

LabelEncoder()

In [15]:
le_dept.transform(['sales','support'])

array([7, 8], dtype=int32)

In [16]:
le_dept.classes_

array(['IT', 'RandD', 'accounting', 'hr', 'management', 'marketing',
       'product_mng', 'sales', 'support', 'technical'], dtype=object)

In [17]:
hr_data['dept_en'] = le_dept.transform(hr_data.dept)

In [18]:
hr_data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years   dept  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  salary_en  dept_en  
0     low          1        7  
1  medium          2        7  
2  medium          2        7  
3     low          1        7  
4     low          1        7

In [19]:
#getting feature data from the complete information
feature_data = hr_data.drop(columns=['dept','salary','left'])

In [20]:
#splitting feature & target data into train & test
from sklearn.model_selection import train_test_split

In [21]:
trainX, testX, trainY, testY = train_test_split(feature_data, target_data)

In [22]:
trainX[:2]

satisfaction_level  last_evaluation  number_project  \
10389                0.50             0.76               3   
2530                 0.49             0.80               2   

       average_montly_hours  time_spend_company  Work_accident  \
10389                   174                   3              0   
2530                    275                   2              0   

       promotion_last_5years  salary_en  dept_en  
10389                      0          2        7  
2530                       0          1        7

In [23]:

# Observation : You are not training the model with string information

### Classification Algorithms
LogisticRegression, RandomForestClassifier, DecisicionTreeClassifier

In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
rf = RandomForestClassifier()

In [26]:
rf.fit(trainX,trainY)

C:\Users\saket\Anaconda333\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [27]:
data = [0.38,0.53,2,157,3,1,0,'support','high']

In [28]:
le_salary.transform(['high'])

array([0], dtype=int32)

In [29]:
le_dept.transform(['support'])

array([8], dtype=int32)

In [30]:
rf.predict(testX)

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [31]:
rf.score(testX,testY)

0.9890666666666666

In [32]:
from sklearn.linear_model import LogisticRegression

In [33]:
lr = LogisticRegression()

In [34]:
lr.fit(trainX,trainY)

C:\Users\saket\Anaconda333\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [35]:
lr.score(testX,testY)

0.7677333333333334

In [36]:
lr.predict(testX)

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [37]:
testX['lr_predict'] = lr.predict(testX)

C:\Users\saket\Anaconda333\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [38]:
testX['rf_predict'] = rf.predict(testX.drop(columns=['lr_predict']))

C:\Users\saket\Anaconda333\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [39]:
testX['actual'] = testY

C:\Users\saket\Anaconda333\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [40]:
testX.head()

satisfaction_level  last_evaluation  number_project  \
6827                 0.53             0.82               3   
8671                 0.58             0.94               4   
12768                0.10             0.84               6   
1415                 0.20             0.90               6   
5443                 0.62             0.74               4   

       average_montly_hours  time_spend_company  Work_accident  \
6827                    133                   3              0   
8671                    225                   2              0   
12768                   293                   5              0   
1415                    138                   3              0   
5443                    173                   2              0   

       promotion_last_5years  salary_en  dept_en  lr_predict  rf_predict  \
6827                       0          2        3           0           0   
8671                       0          1        9           0           0   
12768                      0          2        5           1           1   
1415                       0          1        9           0           0   
5443                       0          2        7           0           0   

       actual  
6827        0  
8671        0  
12768       1  
1415        1  
5443        0

In [41]:
testX[testX.actual != testX.rf_predict]

satisfaction_level  last_evaluation  number_project  \
1415                 0.20             0.90               6   
14780                0.25             0.46               4   
279                  0.82             0.81               4   
5697                 0.81             0.98               6   
827                  0.70             0.74               6   
1576                 0.60             0.85               3   
1199                 0.75             0.74               6   
1831                 0.14             0.47               4   
931                  0.90             0.92               5   
7443                 0.85             0.96               4   
1335                 0.87             0.90               3   
1557                 0.50             0.85               4   
10237                0.88             0.81               4   
1541                 0.61             0.46               5   
569                  0.25             0.46               4   
4455                 0.68             1.00               6   
6358                 0.81             0.98               5   
1005                 0.54             0.56               4   
14981                0.73             0.93               5   
1669                 0.67             0.54               3   
1564                 0.12             0.80               5   
1494                 0.17             0.75               3   
14901                0.11             0.93               5   
1836                 0.61             0.58               2   
1348                 0.89             0.83               5   
788                  0.78             0.81               3   
1289                 0.43             0.56               6   
1762                 0.41             0.71               3   
2415                 0.92             0.97               4   
1988                 0.51             0.60               7   
6263                 0.90             0.87               4   
1690                 0.45             0.68               4   
683                  0.86             0.98               3   
813                  0.15             0.55               6   
10546                0.13             0.61               6   
7762                 0.82             0.87               5   
965                  0.80             0.63               5   
1865                 0.11             0.93               5   
732                  0.85             0.58               3   
1778                 0.85             0.90               2   
14490                0.82             0.81               4   

       average_montly_hours  time_spend_company  Work_accident  \
1415                    138                   3              0   
14780                   214                   4              0   
279                     233                   4              1   
5697                    196                   2              0   
827                     136                   3              0   
1576                    250                   2              0   
1199                    134                   3              0   
1831                    175                   2              0   
931                     154                   4              0   
7443                    240                   6              0   
1335                    307                   5              0   
1557                    138                   3              0   
10237                   235                   6              0   
1541                    220                   4              0   
569                     214                   4              0   
4455                    258                   5              0   
6358                    243                   6              0   
1005                    260                   3              0   
14981                   162                   4              0   
1669                    166                   5              0   
1564            