### 05-03-2020

### classification problem
<hr>

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
hr_data = pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/HR_comma_sep.csv.txt')
hr_data.rename(columns={'sales':'dept'},inplace=True)

In [3]:
hr_data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years   dept  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [4]:
hr_data.left.value_counts()

0    11428
1     3571
Name: left, dtype: int64

### infarences
* Target is descrete in nature so it is a classification problem

In [5]:
target_data = hr_data.left

In [6]:
target_data.head()

0    1
1    1
2    1
3    1
4    1
Name: left, dtype: int64

### Taking care of categorical columns
* dept & salary are categorical data
<hr>
* ML Algorithms only understands numeric data
<hr>
* we will use preprocessor LabelEncoder to convert categorical data to numeric data
<hr>

In [7]:
from sklearn.preprocessing import LabelEncoder

In [9]:
#le.fit will train the tranisformer

In [12]:
le_salary = LabelEncoder()

In [13]:
le_salary.fit(hr_data.salary)

LabelEncoder()

In [15]:
#le_salary.transform(['low'])

array([1], dtype=int32)

In [16]:
#creating new column
hr_data['salary_en'] = le_salary.transform(hr_data.salary)

In [17]:
hr_data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years   dept  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  salary_en  
0     low          1  
1  medium          2  
2  medium          2  
3     low          1  
4     low          1

##### *we can also use fit_transform

In [18]:
#for department

In [19]:
le_dept = LabelEncoder()

In [20]:
le_dept.fit(hr_data.dept)

LabelEncoder()

In [21]:
le_dept.transform(['sales'])

array([7], dtype=int32)

In [22]:
hr_data['dept_en'] = le_dept.transform(hr_data.dept)

In [23]:
hr_data.head(1)

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   

   time_spend_company  Work_accident  left  promotion_last_5years   dept  \
0                   3              0     1                      0  sales   

  salary  salary_en  dept_en  
0    low          1        7

In [24]:
le_dept.classes_

array(['IT', 'RandD', 'accounting', 'hr', 'management', 'marketing',
       'product_mng', 'sales', 'support', 'technical'], dtype=object)

In [29]:
#getting feature data from the hr_data
feature_data = hr_data.drop(columns = ['salary','left','dept'])

In [28]:
feature_data.columns

Index(['satisfaction_level', 'last_evaluation', 'number_project',
       'average_montly_hours', 'time_spend_company', 'Work_accident',
       'promotion_last_5years', 'salary_en', 'dept_en'],
      dtype='object')

##### splitting traget data and feature data into test and train data

In [31]:
from sklearn.model_selection import train_test_split

In [35]:
trainX,testX,trainY,testY = train_test_split(feature_data,target_data)

In [41]:
trainX [:2]

satisfaction_level  last_evaluation  number_project  \
7293                0.97             0.64               4   
7479                0.65             0.97               3   

      average_montly_hours  time_spend_company  Work_accident  \
7293                   152                   2              0   
7479                   198                   3              0   

      promotion_last_5years  salary_en  dept_en  
7293                      0          2        9  
7479                      0          1        1

###### observation: we are not training a data with string information
<hr>

### Classification Algorithms
*Logistic Regression,RandomForestClassifier,DecisiconTree classifier

In [42]:
from sklearn.ensemble import RandomForestClassifier

In [43]:
rf = RandomForestClassifier()

In [44]:
rf.fit(trainX,trainY)

C:\Users\saket\Anaconda333\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [45]:
data = [0.38,0.53,2,157,3,1,0,7,2]

In [46]:
rf.predict([data])

array([1], dtype=int64)

In [49]:
rf.predict(trainX)

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [50]:
rf.score(testX,testY)

0.9888

In [51]:
from sklearn.linear_model import LogisticRegression

In [52]:
lr = LogisticRegression()

In [53]:
lr.fit(trainX,trainY)

C:\Users\saket\Anaconda333\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [54]:
lr.score(testX,testY)

0.7613333333333333

In [55]:
testX['lr_predict'] = lr.predict(testX)

C:\Users\saket\Anaconda333\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [56]:
testX['rf_predict'] = rf.predict(testX.drop(columns=['lr_predict']))

C:\Users\saket\Anaconda333\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [57]:
testX['actual'] = testY

C:\Users\saket\Anaconda333\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [58]:
testX.head()

satisfaction_level  last_evaluation  number_project  \
4648                 0.64             0.40               3   
3837                 0.76             0.65               3   
2675                 0.87             0.90               4   
11955                0.83             0.76               2   
13585                0.98             0.89               4   

       average_montly_hours  time_spend_company  Work_accident  \
4648                    248                   3              0   
3837                    220                   3              0   
2675                    214                   3              0   
11955                   255                   7              0   
13585                   218                   2              0   

       promotion_last_5years  salary_en  dept_en  lr_predict  rf_predict  \
4648                       0          2        6           0           0   
3837                       0          1        7           0           0   
2675                       0          2        9           0           0   
11955                      0          1        7           0           0   
13585                      0          2        7           0           0   

       actual  
4648        0  
3837        0  
2675        0  
11955       0  
13585       0

In [59]:
testX[testX.actual != testX.rf_predict]

satisfaction_level  last_evaluation  number_project  \
1576                 0.60             0.85               3   
5374                 0.58             0.62               5   
1406                 0.15             0.62               4   
12430                0.89             0.65               5   
1238                 0.66             1.00               5   
1450                 0.78             0.78               4   
14734                0.74             0.82               4   
1064                 0.47             0.81               4   
1909                 0.14             0.75               4   
1160                 0.36             0.73               4   
1721                 0.26             0.46               2   
790                  0.23             0.99               4   
1703                 0.73             0.99               6   
1305                 0.62             0.77               5   
1835                 0.54             0.83               6   
1309                 0.56             0.75               5   
1348                 0.89             0.83               5   
14378                0.31             0.54               5   
12704                0.74             0.54               5   
2415                 0.92             0.97               4   
1580                 0.49             0.73               4   
1427                 0.57             0.61               4   
1494                 0.17             0.75               3   
6466                 0.39             0.57               2   
12523                0.74             0.82               4   
927                  0.46             0.86               2   
14641                0.89             0.65               5   
1345                 0.38             1.00               5   
14281                0.74             0.99               2   
523                  0.74             0.82               4   
1665                 0.14             0.55               6   
14945                0.14             0.75               4   
1415                 0.20             0.90               6   
1926                 0.78             0.66               3   
5565                 0.84             0.84               6   
1728                 0.23             0.70               5   
1005                 0.54             0.56               4   
12070                0.74             0.99               2   
1609                 0.85             1.00               6   
12167                0.31             0.54               5   
7077                 0.90             0.85               4   
70                   0.74             0.99               2   

       average_montly_hours  time_spend_company  Work_accident  \
1576                    250                   2              0   
5374                    184                   3              0   
1406                    257                   3              0   
12430                   195                   6              0   
1238                    269                   5              0   
1450                    260                   5              0   
14734                   239                   6              0   
1064                    133                   3              0   
1909                    277                   5              1   
1160                    276                   2              0   
1721                    242                   3              0   
790                     204                   4              1   
1703                    206                   5              0   
1305                    227                   4              0   
1835                    165                   6              0   
1309                    236                   2              0   
1348                    130                   4              1   
14378                   132                   5              0   
12704                   216                   3              0   
2415                