## 13-04-2020


### implementing Nearest Neighbors without sklearn
* recap of nearest neighbors 
* Implement Nearest neighbors Classifier

### Algo :
1. During Training , data are stored in an optimized data structure suited for fast search
2. During prediction, for each data we search for the nearest neighbors using ecclidean/manhatten/humming distence vector calculation technique
3. Finally decide based on majority 

In [1]:
from sklearn.datasets import load_iris

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns; sns.set(color_codes=True)
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
%matplotlib inline


In [3]:
iris = load_iris()

In [4]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
df = pd.DataFrame(iris.data,columns=iris.feature_names)

In [8]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
df['type'] = iris.target

In [10]:
df.sample(5)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
98                 5.1               2.5                3.0               1.1   
141                6.9               3.1                5.1               2.3   
63                 6.1               2.9                4.7               1.4   
129                7.2               3.0                5.8               1.6   
43                 5.0               3.5                1.6               0.6   

     type  
98      1  
141     2  
63      1  
129     2  
43      0

In [11]:
def calculate_distance_between_vectors(v1,v2):
    pass

In [12]:
def store_training_data(data):
    pass

In [13]:
def find_k_neighbors(k,data):
    pass

In [14]:
def identify_class_from_neighbours(neighbours):
    pass

In [27]:
class MyKNN:
    def __init__(self,k=5):
        self.k=k
    
    def my_fit(self,feature_data,target_data):
        self.feature_data = np.array(feature_data)
        self.target_data = np.array(target_data)
    
    def calculate_distance_vector_matrix(self,one_data):
        distences = np.sqrt(np.sum(np.square(self.feature_data - one_data),axis = 1))
        return distences
    
    def find_k_neighbours(self,one_data_feature):
        res =  self.calculate_distance_vector_matrix(one_data_feature)
        return res.argsort()[:self.k]
            
    
    def find_k_neighbours_class(self, one_data_feature):
        indexs_of_neighbours = self.find_k_neighbours(one_data_feature)
        return self.target_data[indexs_of_neighbours]
 
    def my_predict(self, one_data_feature):
        classes = self.find_k_neighbours_class(one_data_feature)
        return np.bincount(classes).argmax()
        

In [28]:
model = MyKNN(k=5)

In [29]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'type'],
      dtype='object')

In [30]:
feature_data = df.drop(columns=['type'],axis=1)
target_data = df.type

In [31]:
model.my_fit(feature_data,target_data)

In [32]:
comp_data = np.array(feature_data)

In [33]:
one_data = np.array([1,2,3,4])

* can we calculate eucludian distance between one_data and comp_data in one shot
* below is euclidean disence between one_data and allthe comp_data

In [34]:
np.sqrt(np.sum(np.square(comp_data - one_data),axis = 1))[:5]

array([6.00499792, 5.76281181, 5.69736781, 5.55517776, 5.96322061])

In [35]:
res = model.find_k_neighbours(one_data)

In [36]:
res.argsort()[:5]

array([1, 3, 2, 4, 0], dtype=int32)

In [37]:
res.argmin()

1

In [38]:
model.find_k_neighbours_class(one_data)


array([2, 1, 1, 1, 1])

In [39]:
np.bincount(res).argmax()


57

In [40]:
model.my_predict([4,4,4,4])

2