### `NumPy Graded Test 1


### 1. Count The Number Of Times Each Value Appears In An Array Of Integers

In [1]:
import numpy as np
import collections
data =  np.array([1,3,55,6,2,1,1,1,5,55,55,6,55,6,6,6,])
collections.Counter(data)

Counter({1: 4, 3: 1, 55: 4, 6: 5, 2: 1, 5: 1})

### 2. Given 9 Integers. You have to convert them into 3*3 Numpy array using Reshape function.

In [2]:
data = np.array([1,2,3,4,5,6,7,8,9])
np.reshape(data,(3,3))


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 3. How to find the memory size of any array¶

In [3]:
data = np.array([1,2,3,4,5,6,7,8,9])
d_size = data.size*data.itemsize
print(d_size)

36


### Create a 2d array of size 10 by 10 with 1 on the border and 0 inside.

In [4]:
data = np.ones((10,10))
data[1:-1,1:-1] = 0
data

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### 5.Create a 8x8 matrix and fill it with a checkerboard pattern.

In [5]:
data = np.ones((8,8))
data[1::2,::2] = 0
data[::2,1::2] = 0
data

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

### 6. Normalize a 5x5 random matrix.¶

In [6]:
#normalization formula : ((a-mean(a))/std(a))
a = np.random.randint(11,66,(5,5))
(a-np.mean(a))/np.std(a)

array([[-0.90381221, -0.18128792,  0.73828847, -1.1008643 ,  0.54123638],
       [-0.64107611, -1.3636004 ,  1.19807666,  1.7892329 ,  1.32944471],
       [ 0.40986833, -0.64107611,  0.73828847, -1.42928443,  0.47555236],
       [-0.04991986, -1.03518027, -1.1008643 ,  1.52649679,  1.59218082],
       [-0.64107611, -1.29791638,  0.3441843 , -0.70676013,  0.40986833]])

### 7. Given a 1D array in range(0,11), negate all elements which are between 3 and 8, in place.

In [7]:
arr = np.arange(0,12)
c=np.where((arr>3) & (arr<8) ,arr*-1,arr)
c

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11])

### 8. How to get the dates of yesterday, today and tomorrow?

In [8]:
today = np.datetime64('today','D')
print("today's date:",today)
yesterday = today - np.timedelta64(1, 'D')
print("yesterday's date:",yesterday)
tomorrow =  today + np.timedelta64(1, 'D')
print("tomorrow's date:",tomorrow)

today's date: 2020-02-18
yesterday's date: 2020-02-17
tomorrow's date: 2020-02-19


### 9. Generate two arrays of size 2X4 & 3X3, find difference between them.

In [9]:
a = np.random.randint(1,22,(2,4))
b = np.random.randint(1,22,(3,3))
np.diff(a,b)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 10. Given 1d array of ['cat','dog','rat'], genrate 100 elements of 1d array consisting of the above 3 value ?
['cat','cat',...,'rat','dog','dog','cat'...]

In [ ]:
data = np.array(['cat','dog','rat'])
x = np.random.choice(data,size = 100)
print(x)

### 11. Create a vector of size 10 with values ranging from 0 to 1, both excluded without manually deducing the values¶

In [ ]:
data = np.linspace(0,1,12,endpoint=True)[1:-1]
print(data)


### 12. Given a two dimensional array, how to extract unique rows?

In [ ]:
data = np.random.randint(1,20,(2,2))
print(data)
x = np.unique(data,axis = 1)
print(x)

### 13. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area.¶

### 14. How to find the closest value (to a given scalar) in a vector?

In [15]:
data = np.arange(20)
data
value = 15.25
c_value = data[np.abs(data-value).argmin()]
print("closest_value :",c_value)

closest_value : 15


### 15. Consider a random vector with shape (10,2) representing coordinates, find point by point distances. Use euclidian distance.

In [18]:
data = np.random.randint(1,100,(10,2))
x,y = np.atleast_2d(data[:,0], data[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[  0.          12.16552506  62.36184731  82.09750301  74.21590126
   56.8594759   43.41658669  41.10960958  66.40783086  23.02172887]
 [ 12.16552506   0.          73.54590403  93.29523032  85.51023331
   55.10898293  52.35456045  40.02499219  78.44743463  34.43835072]
 [ 62.36184731  73.54590403   0.          63.50590524  12.04159458
  107.93516572  27.85677655  67.41661516  38.11823711  50.80354318]
 [ 82.09750301  93.29523032  63.50590524   0.          64.12487817
   91.19758769  80.5294977  112.29425631  25.49509757  59.07622195]
 [ 74.21590126  85.51023331  12.04159458  64.12487817   0.
  118.00423721  39.05124838  78.44743463  40.02499219  61.40032573]
 [ 56.8594759   55.10898293 107.93516572  91.19758769 118.00423721
    0.          97.41663102  95.12623192  91.41662868  57.31491952]
 [ 43.41658669  52.35456045  27.85677655  80.5294977   39.05124838
   97.41663102   0.          39.56008089  56.08029957  42.72001873]
 [ 41.10960958  40.02499219  67.41661516 112.29425631  78.44743

### 16. How to sort an array by the nth column?¶

In [21]:
data = np.random.randint(0,20,(3,3))
print(data)
print(data[data[:,1].argsort()])

[[12 14  9]
 [ 9  0  6]
 [ 4 19 16]]
[[ 9  0  6]
 [12 14  9]
 [ 4 19 16]]


### 17.How to tell if a given 2D array has null columns?

In [23]:
data = np.random.randint(1,50,(3,3))
print(data.any(axis = 0).any())


True


### 18. Considering a two dimensions array, how to get sum over the last two columns at once?

In [27]:
data = np.random.randint(1,50,(3,3))
print(data)
x = np.sum(data[:, 1:])
print(x)

[[32 37 11]
 [ 2 42 40]
 [ 2 34 13]]
177


### 19. Given a 2d array of 5X5, increment 1st column by 1, second column by 2, 3rd column by 3 & so on till the last column

### 20. Given a 1d array(size 100) of boolean values, identify total number of True in it.

In [40]:
data = np.random.choice([True,False],size = 100)
print(data)
print(np.sum(data))

[False False False False  True  True False  True  True  True  True False
  True False  True False False False  True  True  True  True False False
 False  True False False False  True False False  True False  True False
 False False  True False  True  True False  True False False False False
  True  True  True False  True False  True  True  True  True  True False
  True  True False  True False False  True False False False  True False
 False  True False False  True  True  True  True  True  True  True False
 False False  True False  True  True  True  True False False  True False
 False  True False False]
49


### How to get n largest value of an array?

In [49]:
data = np.array([1,2,3,11,5,55,6])
print(data)
np.random.shuffle(data)
n = 3
print (data[np.argsort(data)[-n:]])

[ 1  2  3 11  5 55  6]
[ 6 11 55]


### Given two random arrays of shape 5X5, identify the common elements between them

### 25. How to get index of top two highest value in a 1d array?
[2,22,11,-11,33,7,13,872,-23]

In [53]:
data = np.array([2,22,11,-11,33,7,13,872,-23])
n = 2
idx = (-data).argsort()[:n]
print(idx)

[7 4]
