### 1. Write a NumPy program to get the numpy version and show numpy build configuration.
Level: Easy

In [1]:
import numpy as np
print(np.version.version)
print(np.__config__)

1.15.4
<module 'numpy.__config__' from 'C:\\Users\\saket\\Anaconda333\\lib\\site-packages\\numpy\\__config__.py'>


### 2. Create a null vector of size 10 but the fifth value which is 1.
Level: Easy


In [2]:
df = np.zeros(10)
df[4] = 1
print(df)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### Create a vector with values ranging from 10 to 49.
Level: Easy

In [3]:
import random
df = np.arange(10,50)
df

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3. create two arrays and stack them vertically
Level: Easy

In [4]:
a = np.random.randint(1,100,(4,3))
b = np.random.randint(1,100,(4,3))
c = np.vstack([a,b])
print(c)



[[41 54 43]
 [91 51 14]
 [52 92 71]
 [14 22 53]
 [59 17 71]
 [11  7  4]
 [50 48 35]
 [76 22 83]]


### 4. Reverse a vector (first element becomes last).
Level: Easy

In [5]:
z = np.array([5,55,555])
rev = z[::-1]
print(rev)

[555  55   5]


### 5. Create a 3x3 matrix with values ranging from 0 to 8
Level: Easy

In [6]:
m = np.random.randint(0,8,(3,3))
m

array([[7, 3, 3],
       [1, 1, 1],
       [3, 2, 7]])

### 6. Find indices of non-zero elements from [1,2,0,0,4,0]
Level: Easy

In [7]:
x = np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4], dtype=int32),)

### 7. Create a 10x10 array with random values and find the minimum and maximum values.
Level: Easy

In [8]:
x = np.random.randint(10,101,(10,10))
print(x)
y = np.max(x)
z = np.min(x)
print(y)
print(z)

[[ 67  22  61 100  95 100  59  98  45  47]
 [ 84  58  71  82  20  27  88  77  88  76]
 [ 52  91  97  53  68  34  93  22  88  40]
 [ 26  39  73  75  80  18  20  92  96  94]
 [ 86  30  11  96  23  18  43  74  50  64]
 [ 13  21  95  97  57  84  79  65  30  25]
 [ 52  75  42  99  68  98  83  80  28  59]
 [ 36  47  31  66  16  52  34  60  86  61]
 [ 25  33  29  26  74  10  13  91  94  49]
 [ 54  59  20  45  33  95  71  26  63  62]]
100
10


### 8. Create a random vector of size 30 and find the mean value.¶

In [9]:
x = np.random.random(30)
print(x)
y = np.mean(x)
print("mean:",y)
np.size(x)

[0.44081671 0.61544401 0.19979704 0.32373115 0.60888603 0.04088852
 0.68440395 0.50516386 0.90271236 0.34633648 0.01637014 0.28232993
 0.94247846 0.77105852 0.30673951 0.94350409 0.03679849 0.32101551
 0.999463   0.1144931  0.19497346 0.59452581 0.43208233 0.78486658
 0.66179619 0.59227177 0.78915183 0.51767182 0.02026998 0.03982423]
mean: 0.4676621625958618


30

### 9. Create a 2d array with 1 on the border and 0 inside
Level: Medium

In [10]:
df = np.ones((5,5))
df[1:-1,1:-1]=0
print(df)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### 10. How to add a border (filled with 0's) around an existing array
Level: Medium

In [13]:
df = np.ones((5,5))
df
np.pad(df,(1,1),mode = 'constant')

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Sample Output:

[[ 0. 0. 0. 0. 0.] [ 1. 0. 0. 0. 0.] [ 0. 2. 0. 0. 0.] [ 0. 0. 3. 0. 0.] [ 0. 0. 0. 4. 0.]]

Level: Medium

In [18]:
x = np.zeros((5,5))
x
x[1,0] = 1
x[2,1] = 2
x[3,2] = 3
x[4,3] = 4
x

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

### 12. Create a 5*5 matrix with random values and normalize it.
Level: Medium

In [21]:
x = np.random.random((5,5))
y = (x-x.min()/x.max()-x.min())
y

array([[ 0.45696773,  0.25972685,  0.82661848,  0.94656541,  0.91361052],
       [ 0.46854018,  0.2073674 ,  0.76705912,  0.7651688 ,  0.60081102],
       [ 0.52960464,  0.91245666,  0.43926911,  0.5063642 ,  0.69111675],
       [ 0.10640392,  0.04090549, -0.0114321 ,  0.04350756,  0.75307996],
       [ 0.2954947 ,  0.0754582 ,  0.29220781,  0.23333799,  0.33366122]])

### 13. How to find common values between two arrays
Level: Medium

In [27]:
x = np.arange(50)
y = np.arange(10,60)
z = np.intersect1d(x,y)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 14. Consider a generator function that generates 10 integers and use it to build an array
Level: Medium

In [32]:
def generator():
    global a
    a = np.array(np.arange(10))


generator()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 15. Subtract the mean of each row of a matrix
Level: Hard

In [36]:
arr = np.random.random((10,5))
means = np.mean(arr,axis = 1)
print(arr)
print(means)
subs = arr.copy()
for i in range(arr.shape[0]):
    subs[i] = subs[i] - means[i]
print(subs)


[[0.33225123 0.79450262 0.5025475  0.04871502 0.47750236]
 [0.43451742 0.46093889 0.91037345 0.63832339 0.51908205]
 [0.25441788 0.31355132 0.0389981  0.07816832 0.63081453]
 [0.56844956 0.37851814 0.24397094 0.72360686 0.98452455]
 [0.76512965 0.07443089 0.64207139 0.93730471 0.28054442]
 [0.81864902 0.39529512 0.1161891  0.4028697  0.68691869]
 [0.57619751 0.68471511 0.72211887 0.88371831 0.97202909]
 [0.44342539 0.68980148 0.55683534 0.71864281 0.44303059]
 [0.18597343 0.90539169 0.65019312 0.82819479 0.53954076]
 [0.18590329 0.64848006 0.27075769 0.84538831 0.6078501 ]]
[0.43110375 0.59264704 0.26319003 0.57981401 0.53989621 0.48398433
 0.76775578 0.57034712 0.62185876 0.51167589]
[[-0.09885252  0.36339887  0.07144376 -0.38238873  0.04639862]
 [-0.15812962 -0.13170815  0.31772641  0.04567635 -0.07356498]
 [-0.00877215  0.05036129 -0.22419193 -0.18502171  0.3676245 ]
 [-0.01136445 -0.20129587 -0.33584307  0.14379285  0.40471054]
 [ 0.22523344 -0.46546532  0.10217518  0.3974085  -0.2

### 16. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
Level: Hard

In [37]:
a =np.random.randint(0,10,(1,3))
b=np.random.randint(0,10,(3,1))
sums = []
for i in np.nditer(a):
    for j in np.nditer(b):
        sums.append(i+j)
print(np.array(sums).reshape(3,3))

[[ 3  3  4]
 [ 4  4  5]
 [ 9  9 10]]


### 17. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
Level: Hard

In [38]:
v = np.linspace(5, 50, 10)
v

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])