### Data Preprocessing (text)

###### Bag of words methods :
* count vectorizer 
* TfId vectorizer
* Hahing Vectorizer




###### NLTK Package for stemming & Lemitizatiom
* Understanding packages 
* Stemming 
* Lemmitization

In [1]:
import pandas as pd 

In [2]:
df = pd.DataFrame({'Text':[
    'Hello How are you',
    'Great stuff buddy',
    'How are things',
    'Awesome stuff Awesome'
],'Info':[11,22,44,21]})

In [3]:
df

Text  Info
0      Hello How are you    11
1      Great stuff buddy    22
2         How are things    44
3  Awesome stuff Awesome    21

### Points to under stand  
* Text data cannot be used in ML algos 
* they need to be converted into vectors 

### Count Vectorizer 
* Each word is assigned a column
* value in the column represents the count of that work in the text row known as doccument 
* Combination of these doccument is known as Corpus 

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv = CountVectorizer()

In [6]:
cv.fit(df.Text)

CountVectorizer()

In [7]:
cv.vocabulary_

{'hello': 4,
 'how': 5,
 'are': 0,
 'you': 8,
 'great': 3,
 'stuff': 6,
 'buddy': 2,
 'things': 7,
 'awesome': 1}

In [8]:
res = cv.transform(df.Text).toarray()

In [9]:
res

array([[1, 0, 0, 0, 1, 1, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 2, 0, 0, 0, 0, 1, 0, 0]], dtype=int64)

In [10]:
df.shape

(4, 2)

In [11]:
res.shape

(4, 9)

In [12]:
map_df = pd.DataFrame(res)

In [13]:
map_df.shape

(4, 9)

In [14]:
map_df

0  1  2  3  4  5  6  7  8
0  1  0  0  0  1  1  0  0  1
1  0  0  1  1  0  0  1  0  0
2  1  0  0  0  0  1  0  1  0
3  0  2  0  0  0  0  1  0  0

In [15]:
cols = list(map(lambda x:x[0] ,sorted(list(cv.vocabulary_.items()),key=lambda e:e[1])))

In [16]:
cols

['are', 'awesome', 'buddy', 'great', 'hello', 'how', 'stuff', 'things', 'you']

In [17]:
map_df.columns = cols

In [18]:
map_df

are  awesome  buddy  great  hello  how  stuff  things  you
0    1        0      0      0      1    1      0       0    1
1    0        0      1      1      0    0      1       0    0
2    1        0      0      0      0    1      0       1    0
3    0        2      0      0      0    0      1       0    0

In [19]:
df

Text  Info
0      Hello How are you    11
1      Great stuff buddy    22
2         How are things    44
3  Awesome stuff Awesome    21

In [20]:
cv.transform(['you are great']).toarray()

array([[1, 0, 0, 1, 0, 0, 0, 0, 1]], dtype=int64)

In [21]:
cv.transform(['you are great coder']).toarray()

array([[1, 0, 0, 1, 0, 0, 0, 0, 1]], dtype=int64)

In [22]:
map_df['Info'] = df.Info

In [23]:
map_df

are  awesome  buddy  great  hello  how  stuff  things  you  Info
0    1        0      0      0      1    1      0       0    1    11
1    0        0      1      1      0    0      1       0    0    22
2    1        0      0      0      0    1      0       1    0    44
3    0        2      0      0      0    0      1       0    0    21

In [24]:
cv = CountVectorizer(stop_words = ['are'])

In [25]:
cv.fit(df.Text)

CountVectorizer(stop_words=['are'])

In [26]:
cv.vocabulary_

{'hello': 3,
 'how': 4,
 'you': 7,
 'great': 2,
 'stuff': 5,
 'buddy': 1,
 'things': 6,
 'awesome': 0}

* At very high dimmension (number of feartures),estimators/algorithms dont work well
* Number of possibility of words increases dimenson of the data 
* Stop_words reduces the data 
* we can use stop_words = 'English', to autometically reduce the data 
* Another Technique is vocabulary 

In [27]:
cv = CountVectorizer(stop_words='english')

In [28]:
cv.fit(df.Text)

CountVectorizer(stop_words='english')

In [29]:
cv.vocabulary_

{'hello': 3, 'great': 2, 'stuff': 4, 'buddy': 1, 'things': 5, 'awesome': 0}

In [30]:
cv.transform(df.Text).toarray()

array([[0, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [2, 0, 0, 0, 1, 0]], dtype=int64)

In [31]:
cv = CountVectorizer(vocabulary=['great','buddy','awesome'])

In [32]:
cv.fit(df.Text)

CountVectorizer(vocabulary=['great', 'buddy', 'awesome'])

In [33]:
cv.vocabulary_

{'great': 0, 'buddy': 1, 'awesome': 2}

In [34]:
cv.transform(df.Text).toarray()

array([[0, 0, 0],
       [1, 1, 0],
       [0, 0, 0],
       [0, 0, 2]], dtype=int64)

* some times combination of words are important than singlar words 

In [35]:
cv = CountVectorizer(ngram_range=[1,2],stop_words= 'english')

In [36]:
cv.fit(df.Text)

CountVectorizer(ngram_range=[1, 2], stop_words='english')

In [37]:
cv.vocabulary_

{'hello': 5,
 'great': 3,
 'stuff': 6,
 'buddy': 2,
 'great stuff': 4,
 'stuff buddy': 8,
 'things': 9,
 'awesome': 0,
 'awesome stuff': 1,
 'stuff awesome': 7}

In [38]:
cv.transform(df.Text).toarray()

array([[0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [2, 1, 0, 0, 0, 0, 1, 1, 0, 0]], dtype=int64)

### TF-IDF vectorizer 
* It's a meassure of orginality of words by comparing the number of times a word appears in doc with the number of times the word appears in the corpus
* Lets assume there are 1000 docs(each text) in the corpus (contains all the docs)
* words like 'is','are','the' appears in all the docs 
* words like 'nuclear','prime-minister' appears only in few docs but multiple times 
* TF-IDF = TF(t,d) * IDF(t)
* IDF(t) = log(1+no. of doc / 1 + df(d,t) +1)


In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [40]:
tfidf = TfidfVectorizer(stop_words='english')

In [41]:
tfidf.fit(df.Text)

TfidfVectorizer(stop_words='english')

In [42]:
import numpy as np
np.round(tfidf.transform(df.Text).toarray(),2)

array([[0.  , 0.  , 0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.62, 0.62, 0.  , 0.49, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 1.  ],
       [0.93, 0.  , 0.  , 0.  , 0.37, 0.  ]])

In [43]:
tfidf.vocabulary_

{'hello': 3, 'great': 2, 'stuff': 4, 'buddy': 1, 'things': 5, 'awesome': 0}

### Hashing vectorizer
* The above two approaches builds feature with high dimension
* Using Hashing vectorizer you can restirict the number of dimension 
* Useful when the data is very high dimensional 

In [44]:
from sklearn.feature_extraction.text import HashingVectorizer

In [45]:
hv = HashingVectorizer(n_features =4)

In [46]:
hv.fit(df.Text)

HashingVectorizer(n_features=4)

In [47]:
hv.transform(df.Text).toarray()

array([[ 0.81649658, -0.40824829,  0.        ,  0.40824829],
       [ 0.57735027, -0.57735027,  0.57735027,  0.        ],
       [ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.4472136 ,  0.        ,  0.89442719]])

### NLTK [Natural Language Toolkit]
* Run,ran,runs,running can be mapped into one column 