### Topics 
* Recap of linear regression & classification 
* solving simple problem with regressiom and classification


### Regression
* Feature Data/Independent Variables -> (Sqft,Floor,TotalFloor,Bedroom,Living.Room,Bathroom)
* Target Data/Dependent Variable -> Price

In [1]:
 import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline

In [6]:
house_data = pd.read_csv("https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/house_rental_data.csv.txt",index_col = 'Unnamed: 0')

In [7]:
house_data.head()

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom  Price
1  1177.698      2           7        2            2         2  62000
2  2134.800      5           7        4            2         2  78000
3  1138.560      5           7        2            2         1  58000
4  1458.780      2           7        3            2         2  45000
5   967.776     11          14        3            2         2  45000

In [10]:
house_data.sample(3)

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom   Price
220  1903.53      8          13        3            2         2  120000
162  1565.52      2           6        3            2         1   45000
87   3255.57      4           7        4            2         4  130000

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
lr = LinearRegression()

In [13]:
feature_data = house_data.drop('Price',axis=1)

In [14]:
target_data = house_data.Price

In [15]:
feature_data.head()

Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom
1  1177.698      2           7        2            2         2
2  2134.800      5           7        4            2         2
3  1138.560      5           7        2            2         1
4  1458.780      2           7        3            2         2
5   967.776     11          14        3            2         2

In [16]:
from sklearn.model_selection import train_test_split

In [25]:
trainX,testX,trainY,testY = train_test_split(feature_data,target_data)

In [26]:
trainX.shape

(483, 6)

In [27]:
house_data.shape

(645, 7)

In [28]:
testX.shape

(162, 6)

In [29]:
lr.fit(trainX,trainY)

LinearRegression()

In [30]:
lr.predict(testX[:2])

array([51839.87188541, 54644.92516016])

In [31]:
testX[:2]


Sqft  Floor  TotalFloor  Bedroom  Living.Room  Bathroom
369   537.258     22          26        1            0         1
550  1529.940      2           7        4            2         2

In [32]:
testY[:2]

369    19000
550    45000
Name: Price, dtype: int64

###  S12

In [34]:
air_data = pd.read_excel("C:\\Users\\saket\\Downloads\\jupyter notebook\\edyoda data\\AirQualityUCI.xlsx")

In [36]:
air_data.head()

Date      Time  CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  \
0 2004-03-10  18:00:00     2.6      1360.00       150  11.881723   
1 2004-03-10  19:00:00     2.0      1292.25       112   9.397165   
2 2004-03-10  20:00:00     2.2      1402.00        88   8.997817   
3 2004-03-10  21:00:00     2.2      1375.50        80   9.228796   
4 2004-03-10  22:00:00     1.6      1272.25        51   6.518224   

   PT08.S2(NMHC)  NOx(GT)  PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)  \
0        1045.50    166.0       1056.25    113.0       1692.00      1267.50   
1         954.75    103.0       1173.75     92.0       1558.75       972.25   
2         939.25    131.0       1140.00    114.0       1554.50      1074.00   
3         948.25    172.0       1092.00    122.0       1583.75      1203.25   
4         835.50    131.0       1205.00    116.0       1490.00      1110.00   

       T         RH        AH  
0  13.60  48.875001  0.757754  
1  13.30  47.700000  0.725487  
2  11.90  53.975000  0.750239  
3  11.00  60.000000  0.786713  
4  11.15  59.575001  0.788794

In [37]:
air_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   Date           9357 non-null   datetime64[ns]
 1   Time           9357 non-null   object        
 2   CO(GT)         9357 non-null   float64       
 3   PT08.S1(CO)    9357 non-null   float64       
 4   NMHC(GT)       9357 non-null   int64         
 5   C6H6(GT)       9357 non-null   float64       
 6   PT08.S2(NMHC)  9357 non-null   float64       
 7   NOx(GT)        9357 non-null   float64       
 8   PT08.S3(NOx)   9357 non-null   float64       
 9   NO2(GT)        9357 non-null   float64       
 10  PT08.S4(NO2)   9357 non-null   float64       
 11  PT08.S5(O3)    9357 non-null   float64       
 12  T              9357 non-null   float64       
 13  RH             9357 non-null   float64       
 14  AH             9357 non-null   float64       
dtypes: datetime64[ns](1),

In [38]:
target_data = air_data.AH

In [40]:
feature_data = air_data.drop(columns=['Date','Time',"AH"])

In [41]:
feature_data.head()

CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  \
0     2.6      1360.00       150  11.881723        1045.50    166.0   
1     2.0      1292.25       112   9.397165         954.75    103.0   
2     2.2      1402.00        88   8.997817         939.25    131.0   
3     2.2      1375.50        80   9.228796         948.25    172.0   
4     1.6      1272.25        51   6.518224         835.50    131.0   

   PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)      T         RH  
0       1056.25    113.0       1692.00      1267.50  13.60  48.875001  
1       1173.75     92.0       1558.75       972.25  13.30  47.700000  
2       1140.00    114.0       1554.50      1074.00  11.90  53.975000  
3       1092.00    122.0       1583.75      1203.25  11.00  60.000000  
4       1205.00    116.0       1490.00      1110.00  11.15  59.575001

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
trainX,testX,trainY,testY = train_test_split(feature_data,target_data)

In [45]:
#It's regression because target is continues
#These are different  regression algorithms
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor

In [46]:
#Create empty models for these algorithms
dt = DecisionTreeRegressor()
svr = SVR()
rf = RandomForestRegressor()

In [47]:
dt.fit(trainX,trainY)

DecisionTreeRegressor()

In [51]:
testX[1:3]

CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  \
555      3.0      1373.50       415  14.142883        1121.25    180.0   
1149     2.7      1187.25       277  14.791370        1142.00    149.0   

      PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)     T      RH  
555         770.75    146.0       1685.25      1399.25  18.5  43.025  
1149        839.50    110.0       1651.00      1011.25  25.7  23.775

In [52]:
testY[1:3]

555     0.907380
1149    0.773721
Name: AH, dtype: float64

In [53]:
dt.predict(testX[1:3])

array([0.90263472, 0.77963435])

In [54]:
rf.fit(trainX,trainY)
#Generate a mathematical formula & stores in rf object

RandomForestRegressor()

In [55]:
rf.predict(testX[:2])

array([1.60334399, 0.90659679])

In [56]:
testX[:1]

CO(GT)  PT08.S1(CO)  NMHC(GT)   C6H6(GT)  PT08.S2(NMHC)  NOx(GT)  \
5153     2.3      1201.75      -200  12.250535        1058.25    416.0   

      PT08.S3(NOx)  NO2(GT)  PT08.S4(NO2)  PT08.S5(O3)       T         RH  
5153         646.5     82.0        1623.0      1152.25  19.975  69.599999

In [57]:
svr.fit(trainX,trainY)

SVR()

In [58]:
svr.predict(testX[:2])

array([1.38047971, 0.41210165])

In [62]:
hr_data =  pd.read_csv('https://raw.githubusercontent.com/edyoda/data-science-complete-tutorial/master/Data/HR_comma_sep.csv.txt')

In [67]:
hr_data.rename(columns={'sales':'dept'},inplace=True)


In [68]:
hr_data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years   dept  \
0                   3              0     1                      0  sales   
1                   6              0     1                      0  sales   
2                   4              0     1                      0  sales   
3                   5              0     1                      0  sales   
4                   3              0     1                      0  sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

* convert categorical data into cuntinious data 

In [69]:
from sklearn.preprocessing import LabelEncoder

In [70]:
le = LabelEncoder()

In [71]:
hr_data['dept_en'] = le.fit_transform(hr_data.dept)

In [73]:
hr_data.dept_en.value_counts()

7    4140
9    2720
8    2229
0    1227
6     902
5     858
1     787
2     767
3     739
4     630
Name: dept_en, dtype: int64

In [74]:
hr_data.dept.value_counts()

sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: dept, dtype: int64

In [75]:
hr_data['salary_en'] = le.fit_transform(hr_data.salary)

In [76]:
hr_data.salary_en.value_counts()

1    7316
2    6446
0    1237
Name: salary_en, dtype: int64

In [77]:
hr_data.salary.value_counts()

low       7316
medium    6446
high      1237
Name: salary, dtype: int64

In [85]:
feature_data = hr_data.drop(columns=['salary','dept','satisfaction_level','salary_en'])

In [79]:
feature_data.head()

last_evaluation  number_project  average_montly_hours  time_spend_company  \
0             0.53               2                   157                   3   
1             0.86               5                   262                   6   
2             0.88               7                   272                   4   
3             0.87               5                   223                   5   
4             0.52               2                   159                   3   

   Work_accident  left  promotion_last_5years  dept_en  salary_en  
0              0     1                      0        7          1  
1              0     1                      0        7          2  
2              0     1                      0        7          2  
3              0     1                      0        7          1  
4              0     1                      0        7          1

In [86]:
target_data = hr_data.salary_en

In [87]:
dt = DecisionTreeRegressor()

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
trainX, testX, trainY, testY = train_test_split(feature_data, target_data)

In [90]:
dt.fit(trainX,trainY)

DecisionTreeRegressor()

In [91]:
dt.predict(testX[:2])

array([1., 1.])

In [92]:
testX[:2]

last_evaluation  number_project  average_montly_hours  \
9127             0.60               5                   244   
173              0.88               6                   284   

      time_spend_company  Work_accident  left  promotion_last_5years  dept_en  
9127                   3              1     0                      0        9  
173                    4              0     1                      0        7

In [93]:
testY[:2]

9127    1
173     1
Name: salary_en, dtype: int32